version: '3.7'

services:
  n8n:
    build: .
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - WEBHOOK_URL=http://localhost:5678
      - N8N_CORS_ALLOW_ORIGIN=http://localhost:3000
      - N8N_CORS_ALLOW_METHODS=GET,POST,OPTIONS
      - N8N_CORS_ALLOW_HEADERS=Content-Type
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - n8n
    networks:
      - n8n-network

volumes:
  n8n_data:

networks:
  n8n-network:
